#!/bin/bash

nslookup slash16.org | grep Server | awk '{print $2}'

# Domain Name System is the phonebook of the Internet, we access information
# online through domain names. Web browsers interact thorugh IP's (Internet 
# Protocols) addresses. DNS translates domain names to IP addresses.
